<?php 
require('fpdf.php');
include 'db_con.php';

$employee_id = $_GET['id'] ?? 0;
$employee_id = intval($employee_id);

$stmt = $conn->prepare("SELECT * FROM employees WHERE employee_id = ?");
$stmt->bind_param("i", $employee_id);
$stmt->execute();
$result = $stmt->get_result();
$employee = $result->fetch_assoc();
$stmt->close();

if (!$employee) {
    die("Employee not found.");
}

// Create PDF
$pdf = new FPDF();
$pdf->AddPage();

// HEADER
if(file_exists('images/lynn_logo.png')) {
    $pdf->Image('images/lynn_logo.png', 10, 10, 30);
}
$pdf->SetFont('Arial', 'B', 20);
$pdf->SetTextColor(0, 51, 102);
$pdf->Cell(0, 15, 'Employee Profile', 0, 1, 'C');
$pdf->Ln(10);

// Passport at top-left
if(!empty($employee['passport_path']) && file_exists($employee['passport_path'])) {
    $pdf->Image($employee['passport_path'], 15, 35, 40, 40);
}

// Move content *below* the image
$pdf->SetY(80); // Push content below the image

// Employee Details Table
$pdf->SetFont('Arial', '', 12);
$pdf->SetFillColor(224, 235, 255);
$pdf->SetTextColor(0,0,0);
$pdf->SetDrawColor(0,0,0);
$pdf->SetLineWidth(.3);

$details = [
    'Name' => $employee['first_name'].' '.$employee['last_name'],
    'National ID' => $employee['national_id'],
    'KRA PIN' => $employee['kra_pin'],
    'NSSF Number' => $employee['nssf_number'],
    'NHIF Number' => $employee['nhif_number'],
    'Email' => $employee['email'],
    'Phone' => $employee['phone'],
    'Department' => $employee['department'],
    'Position' => $employee['position'],
    'Date of Hire' => $employee['date_of_hire'],
    'Status' => $employee['status'],
    'Employment Type' => $employee['employment_type'] ?? 'Permanent'
];

if($employee['employment_type'] === 'Contract') {
    $details['Contract Start'] = $employee['contract_start'];
    $details['Contract End'] = $employee['contract_end'];
}

// Table below image
$fill = false;
foreach($details as $key => $value) {
    $pdf->SetFont('Arial', 'B', 12);
    $pdf->SetFillColor(224, 235, 255);
    $pdf->Cell(60, 10, $key, 1, 0, 'L', $fill);
    
    $pdf->SetFont('Arial', '', 12);
    $pdf->Cell(0, 10, $value, 1, 1, 'L', $fill);
    
    $fill = !$fill;
}

// Footer
$pdf->Ln(10);
$pdf->SetFont('Arial', 'I', 10);
$pdf->Cell(0, 5, 'Generated by LynnTech Employee Management System', 0, 1, 'C');

$pdf->Output('I', 'Employee_Profile.pdf');
