<?php
require('fpdf.php');
require 'db_con.php';

// ✅ Ensure chemical code is passed
if (!isset($_GET['code'])) {
    die("Chemical code missing.");
}

$chemical_code = trim($_GET['code']);

// ✅ Fetch chemical details
$sql = "SELECT id, chemical_name, chemical_code, main_category, group_name, category, description, created_at 
        FROM chemical_names 
        WHERE chemical_code = ?";
$stmt = $conn->prepare($sql);
$stmt->bind_param("s", $chemical_code);
$stmt->execute();
$chemical = $stmt->get_result()->fetch_assoc();
$stmt->close();

if (!$chemical) {
    die("Chemical not found.");
}

// ✅ Fetch lots for this chemical
$sql = "SELECT 
            batch_no,
            po_number,
            stock_name,
            original_quantity,
            quantity,
            unit,
            unit_cost,
            total_cost,
            created_at
        FROM stock_in
        WHERE stock_code = ?
        ORDER BY created_at ASC";
$stmt = $conn->prepare($sql);
$stmt->bind_param("s", $chemical_code);
$stmt->execute();
$lots = $stmt->get_result();
$stmt->close();

// ✅ Initialize PDF
$pdf = new FPDF('L', 'mm', 'A4');
$pdf->AddPage();

// ✅ Header Section
$pdf->Image('images/lynn_logo.png', 10, 8, 25);
$pdf->SetFont('Arial', 'B', 14);
$pdf->Cell(0, 10, 'LYNNTECH CHEMICALS & EQUIPMENT', 0, 1, 'C');

$pdf->SetFont('Arial', '', 11);
$pdf->Cell(0, 8, 'ENGINEERING LOTS REPORT', 0, 1, 'C');
$pdf->Ln(4);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(0, 8, 'Date: ' . date('d M Y'), 0, 1, 'R');
$pdf->Ln(5);

// ✅ Chemical Details Section
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(0, 7, 'Material Details', 0, 1);
$pdf->SetFont('Arial', '', 9);

$pdf->Cell(50, 7, 'Chemical Name: ' . $chemical['chemical_name'], 0, 1);
$pdf->Cell(50, 7, 'Chemical Code: ' . $chemical['chemical_code'], 0, 1);
$pdf->Cell(50, 7, 'Main Category: ' . ($chemical['main_category'] ?? '-'), 0, 1);
$pdf->Cell(50, 7, 'Group: ' . ($chemical['group_name'] ?? '-'), 0, 1);
$pdf->Cell(50, 7, 'Category: ' . ($chemical['category'] ?? '-'), 0, 1);
$pdf->MultiCell(0, 7, 'Description: ' . ($chemical['description'] ?? '-'), 0, 1);
$pdf->Ln(4);

// ✅ Table Header
$pdf->SetFont('Arial', 'B', 9);
$pdf->SetFillColor(230, 230, 230);
$pdf->Cell(25, 8, 'Batch No', 1, 0, 'C', true);
$pdf->Cell(25, 8, 'PO Number', 1, 0, 'C', true);
$pdf->Cell(50, 8, 'Stock Name', 1, 0, 'C', true);
$pdf->Cell(25, 8, 'Original Qty', 1, 0, 'C', true);
$pdf->Cell(25, 8, 'Remaining Qty', 1, 0, 'C', true);
$pdf->Cell(20, 8, 'Unit', 1, 0, 'C', true);
$pdf->Cell(25, 8, 'Unit Cost', 1, 0, 'C', true);
$pdf->Cell(25, 8, 'Total Cost', 1, 0, 'C', true);
$pdf->Cell(40, 8, 'Date Added', 1, 1, 'C', true);

// ✅ Table Body
$pdf->SetFont('Arial', '', 9);

if ($lots->num_rows > 0) {
    while ($lot = $lots->fetch_assoc()) {
        $pdf->Cell(25, 8, $lot['batch_no'] ?? '-', 1);
        $pdf->Cell(25, 8, 'PO#' . ($lot['po_number'] ?? '-'), 1);
        $pdf->Cell(50, 8, $lot['stock_name'], 1);
        $pdf->Cell(25, 8, $lot['original_quantity'], 1);
        $pdf->Cell(25, 8, $lot['quantity'], 1);
        $pdf->Cell(20, 8, $lot['unit'], 1);
        $pdf->Cell(25, 8, number_format($lot['unit_cost'], 2), 1);
        $pdf->Cell(25, 8, number_format($lot['total_cost'], 2), 1);
        $pdf->Cell(40, 8, $lot['created_at'], 1, 1);
    }
} else {
    $pdf->Cell(260, 8, 'No lots found for this material.', 1, 1, 'C');
}

// ✅ Footer
$pdf->Ln(5);
$pdf->SetFont('Arial', 'I', 9);
$pdf->Cell(0, 10, 'Generated by Lynntech ERP System', 0, 1, 'C');

// ✅ Output
$pdf->Output('D', 'Engineering_Lots_' . $chemical['chemical_code'] . '.pdf');
?>
