<?php
require('fpdf.php');
require 'db_con.php';

// ✅ Fetch engineering products with total remaining
$query = "
    SELECT 
        c.id,
        c.chemical_name AS product_name,
        c.chemical_code AS product_code,
        c.category,
        c.description,
        c.created_at,
        IFNULL(SUM(s.quantity), 0) AS total_remaining
    FROM chemical_names c
    LEFT JOIN stock_in s ON c.chemical_code = s.stock_code
    WHERE c.main_category = 'Engineering Products'
    GROUP BY c.chemical_code
    ORDER BY c.id DESC
";
$result = $conn->query($query);

// ✅ Initialize PDF
$pdf = new FPDF('P', 'mm', 'A4');
$pdf->AddPage();

// ✅ Header Section
$pdf->Image('images/lynn_logo.png', 10, 8, 25);
$pdf->SetFont('Arial', 'B', 14);
$pdf->Cell(0, 10, 'LYNNTECH CHEMICALS & EQUIPMENT', 0, 1, 'C');

$pdf->SetFont('Arial', '', 11);
$pdf->Cell(0, 8, 'ENGINEERING PRODUCTS INVENTORY REPORT', 0, 1, 'C');
$pdf->Ln(5);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(0, 8, 'Date: ' . date('d M Y'), 0, 1, 'R');
$pdf->Ln(5);

// ✅ Table Header
$pdf->SetFont('Arial', 'B', 10);
$pdf->SetFillColor(230, 230, 230);
$pdf->Cell(10, 8, '#', 1, 0, 'C', true);
$pdf->Cell(40, 8, 'Product Name', 1, 0, 'C', true);
$pdf->Cell(30, 8, 'Code', 1, 0, 'C', true);
$pdf->Cell(35, 8, 'Category', 1, 0, 'C', true);
$pdf->Cell(30, 8, 'Remaining', 1, 0, 'C', true);
$pdf->Cell(45, 8, 'Description', 1, 1, 'C', true);

// ✅ Table Body
$pdf->SetFont('Arial', '', 9);
$count = 1;

while ($row = $result->fetch_assoc()) {
    $pdf->Cell(10, 8, $count++, 1);
    $pdf->Cell(40, 8, $row['product_name'], 1);
    $pdf->Cell(30, 8, $row['product_code'], 1);
    $pdf->Cell(35, 8, $row['category'], 1);
    $pdf->Cell(30, 8, number_format($row['total_remaining'], 2) . ' units', 1);
    $pdf->Cell(45, 8, substr($row['description'], 0, 35), 1, 1);
}

// ✅ Footer
$pdf->Ln(5);
$pdf->SetFont('Arial', 'I', 9);
$pdf->Cell(0, 10, 'Generated by Lynntech ERP System', 0, 1, 'C');

// ✅ Output
$pdf->Output('D', 'Engineering_Inventory_Report.pdf');
?>
